### ISSUE TITLE
peach-vps disconnects from ssh after a few minutes

### ISSUE THREAD

**Issue by mhfowler** [peachcloud/peach-vps#12]
I wasn't sure where to put this, but just putting this issue here. 
It's not a big deal, but is somewhat annoying while developing to re-connect. 

@mycognosist do you know if there's any ssh setting on the VPS that would be causing these disconnects? for me it seems like its always specifically with the VPS and after a certain amount of time

**Comment by mycognosist** [comment]
@mhfowler 

Thanks for letting me know about this. Should be all fixed now.
