### ISSUE TITLE
Rename this repo to peach-package-builder

### ISSUE THREAD

**Issue by mhfowler** [peachcloud/peach-vps#8]
Now that we have two repos on the vps doing building, 
this repo, 
and peach-img-builder ...

perhaps we should rename this repo from peach-vps to peach-package-builder?
what do you think @mycognosist?

**Comment by mycognosist** [comment]
@mhfowler 

Thanks for the bump - somehow this had passed me by. Yes, I'm totally onboard with renaming the repo. I really like the clarity and specificity of those naming options.

**Comment by mycognosist** [comment]
Closing this one. Thanks for updating the name!
